### ISSUE TITLE
Error: failed to generate train.json 

### ISSUE THREAD

**Issue by rizarae-p** [ShirleyMaxx/ChimpACT#1]
Hello! Thank you for providing the dataset and code for your interesting project. :)
I followed the installation steps you provided in the README file and ran `process_data.sh`.

The code was able to successfully extract the images using ffmeg and generate the train/test/val directories with the corresponding images and videos. However, I ran into an error when generating `train.json`.
![Screenshot from 2024-04-16 02-58-36](https://github.com/ShirleyMaxx/ChimpACT/assets/64082964/997cb6b2-6cb2-4be7-8ac0-2cad08bb0cd5)

May I ask if you could help me solve this issue?

For reference, this is my directory tree:
![Screenshot from 2024-04-16 03-03-51](https://github.com/ShirleyMaxx/ChimpACT/assets/64082964/57d7b33f-c034-495c-96a8-86682a1522e9)

Thank you so much :)

**Comment by ShirleyMaxx** [comment]
Hi, thank you for your interest in our work. Looking at the error message in the first screenshot, it indicates that the number of frames does not match the number of extracted images. I suspect the issue lies with FFmpeg's image extraction process, meaning that the `images` folder under `ChimpACT_processed` might be incorrect.

**Comment by rizarae-p** [comment]
Thank you for your response. I used your script that contains the ffmepg extraction commands.
How do you suggest we fix this?

**Comment by ShirleyMaxx** [comment]
Could it be that ffmpeg failed to decompress correctly? I've used this script many times without encountering this error.
